# Change these first
owner: NekoGamesRepo # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Neko
    url: https://neko.games
    icon: https://neko.games/wp-content/uploads/2023/01/neko.png
 
    
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://marketing.neko.games
  name: Games Status Page
  introTitle: "**Neko** Status page for neko Games"
  introMessage: This is a page that show the status of neko games
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
